---
  - hosts: server
    tasks:
    - name: ensure apache is present
      become: true
      apt:
        name: apache2
        state: present
    - name: ensure docker-ce exists
      apt:
        name: docker-ce
        state: present